### ISSUE TITLE
Use Boost.Beast in place of websocketpp

### ISSUE THREAD

**Issue by aaronovz1** [mschneider/solcpp#1]
websocketpp hasn't been maintained in a couple years, and since Boost already ships with Beast, it would be better to get rid of an extra thirdparty dependency and use one that comes with boost and is maintained.

https://www.boost.org/doc/libs/1_78_0/libs/beast/doc/html/index.html

**Comment by godmodegalactus** [comment]
Implementing websockets with boost  PR : https://github.com/mschneider/solcpp/pull/77
