### ISSUE TITLE
Use googletest instead/in addition to doctest

### ISSUE THREAD

**Issue by papadpickle** [mschneider/solcpp#3]
googletest has features like value/type parameterized tests which are not <yet> supported by doctest as per the doctest faq. 
https://github.com/doctest/doctest/blob/master/doc/markdown/faq.md#how-is-doctest-different-from-google-test

also gmock can be used out of the box with gtest. doctest could in theory be made to work with gmock, nevertheless someone has to try it out.

https://github.com/google/googletest

**Comment by mschneider** [comment]
i am not opposed to this change, as long as you increase test coverage 🤝

**Comment by papadpickle** [comment]
fair enough.. wanted to know if there was a specific reason for using doctest over something as widespread/mature as gtest. will raise a pr in case i add it. closing this issue now.
